const app=document.querySelector('#app');
const genres=[['Surprise me','✦'],['Comedy','☺'],['Adventure','↗'],['Animation','✳'],['Romance','♡'],['Thriller','ϟ']];
const durations=[['short','Under 90 min','A little escape'],['medium','90–120 min','Movie-night sweet spot'],['any','Any length','I have time']];
const movies=[
['Office Space',1999,89,'Comedy','A burned-out office worker decides to stop caring—and accidentally turns his working life upside down.'],
['What We Do in the Shadows',2014,86,'Comedy','Vampire flatmates navigate chores, nightlife, and the awkward business of being immortal.'],
['The General',1926,78,'Comedy','A determined train engineer chases his stolen locomotive in a silent comedy full of inventive stunts.'],
['School of Rock',2003,109,'Comedy','A would-be rock star turns a classroom of kids into a band with something to prove.'],
['The Grand Budapest Hotel',2014,99,'Comedy','An impeccably mannered concierge and his lobby boy stumble into a colorful, fast-moving caper.'],
['Little Miss Sunshine',2006,101,'Comedy','An eccentric family squeezes into a van for a road trip to a little girl’s beauty pageant.'],
['Fantastic Mr. Fox',2009,87,'Adventure','A charming fox’s last big heist puts his family and woodland neighbors in a wonderfully scrappy showdown.'],
['My Neighbor Totoro',1988,86,'Adventure','Two sisters discover gentle forest spirits near their new countryside home.'],
['Dumbo',1941,64,'Adventure','A little circus elephant discovers that the thing making him different might help him soar.'],
['The Princess Bride',1987,98,'Adventure','True love, sword fights, and very quotable mischief in a warmhearted fairy-tale adventure.'],
['Hunt for the Wilderpeople',2016,101,'Adventure','A rebellious kid and his reluctant guardian become unlikely partners in the New Zealand wilderness.'],
['The Goonies',1985,114,'Adventure','A group of friends follows an old treasure map into one last adventure together.'],
['Toy Story',1995,81,'Animation','A cowboy toy and a new space ranger learn to work together when they’re stranded far from home.'],
['The Iron Giant',1999,86,'Animation','A boy befriends a mysterious giant robot in a moving story about choosing who you want to be.'],
['The Secret of Kells',2009,75,'Animation','A young apprentice ventures beyond his abbey into a beautifully imagined world of forests and folklore.'],
['Spider-Man: Into the Spider-Verse',2018,117,'Animation','Miles Morales discovers his powers—and an entire multiverse of unexpected Spider-friends.'],
['Inside Out',2015,95,'Animation','Five emotions try to help a young girl find her footing after a big move.'],
['Kiki’s Delivery Service',1989,103,'Animation','A young witch starts a delivery business and finds her independence in a seaside city.'],
['Before Sunset',2004,80,'Romance','Two people reconnect in Paris nine years after their first meeting, with just an afternoon to spare.'],
['Once',2007,86,'Romance','Two musicians form an intimate connection while writing songs on the streets of Dublin.'],
['Brief Encounter',1945,86,'Romance','A chance meeting at a railway station becomes a deeply felt, complicated connection.'],
['Before Sunrise',1995,101,'Romance','Two strangers step off a train and spend one unforgettable night wandering through Vienna.'],
['10 Things I Hate About You',1999,97,'Romance','A sharp, funny high-school romance about big personalities and unexpected connections.'],
['(500) Days of Summer',2009,95,'Romance','A hopeful romantic looks back on the bright moments and mixed signals of a relationship.'],
['Phone Booth',2002,81,'Thriller','A man answers a ringing payphone and finds himself trapped in a tense public standoff.'],
['Following',1998,69,'Thriller','A writer’s habit of following strangers pulls him into a maze of deception.'],
['Rope',1948,80,'Thriller','A dinner party becomes a claustrophobic game of suspicion in a single apartment.'],
['Rear Window',1954,112,'Thriller','A photographer watching his neighbors from his apartment suspects he has witnessed a crime.'],
['Searching',2018,102,'Thriller','A father searches for his missing daughter through the digital traces of her life.'],
['The Others',2001,104,'Thriller','A mother and her children begin to sense a mysterious presence in their secluded home.']
].map(([title,year,runtime,genre,description])=>({title,year,runtime,genre,description}));
let state={screen:'home',genre:null,duration:null,deck:[],open:[],locked:false,result:null};let turn=0;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function matches(){return movies.filter(m=>(state.genre==='Surprise me'||m.genre===state.genre)&&(state.duration==='any'||(state.duration==='short'?m.runtime<90:m.runtime>=90&&m.runtime<=120)))}
function top(step){return `<div class="topline"><nav class="screen-navigation" aria-label="Screen navigation"><button class="home-button" data-action="home">⌂ Home</button>${step===3?'<button class="back" data-action="preferences">← Preferences</button>':''}</nav><div class="progress" aria-label="Step ${step} of 3"><span class="active"></span><span class="active"></span><span class="${step===3?'active':''}"></span></div></div>`}
function render(){
 document.body.classList.toggle("landing",state.screen==="home");
 if(state.screen==='home'){app.innerHTML=`<section class="landing-content enter"><h1>Find your movie.<br><span class="accent">Skip the scroll.</span></h1><p class="intro">Two quick questions. One fun matching game.<br>A movie picked for you.</p><button class="primary" data-action="preferences">Find my movie <span class="arrow" aria-hidden="true">→</span></button><img class="landing-illustration" src="hero.png" alt="" width="180" height="180"></section>`}
 else if(state.screen==='preferences'){app.innerHTML=`<section class="screen enter">${top(2)}<span class="step-label">FIRST, THE BASICS</span><h1>What’s tonight feeling like?</h1><p class="sub">Just two quick picks. Then we’ll get to the fun part.</p><fieldset class="question"><legend><span>1</span> What genre are you in the mood for?</legend><div class="options">${genres.map(([g,i])=>`<button class="choice" aria-pressed="${state.genre===g}" data-genre="${g}"><span class="icon" aria-hidden="true">${i}</span>${g}${state.genre===g?'<span class="check">✓</span>':''}</button>`).join('')}</div></fieldset><fieldset class="question length"><legend><span>2</span> How much time do you have?</legend><div class="options">${durations.map(([v,label,sub])=>`<button class="choice" aria-pressed="${state.duration===v}" data-duration="${v}"><strong>${label}${state.duration===v?' ✓':''}</strong><small>${sub}</small></button>`).join('')}</div></fieldset><div class="screen-bottom"><p class="micro">That’s all we need. Your game is next.</p><button class="primary" data-action="play" ${!state.genre||!state.duration?'disabled':''}>Let’s play <span class="arrow">→</span></button></div></section>`}
 else if(state.screen==='game'){app.innerHTML=`<section class="screen game-screen enter">${top(3)}<div class="game-heading"><span class="step-label">TIME FOR A LITTLE PLAY</span><h1>A perfect little match.</h1><p class="sub">Flip two cards. Find a matching pair.<br>Your match unlocks tonight’s movie.</p></div><div class="preference-tags"><span class="tag">${esc(state.genre)}</span><span class="tag">${durations.find(d=>d[0]===state.duration)[1]}</span></div><div class="board" aria-label="Movie matching game">${state.deck.map((c,i)=>`<button class="card" data-card="${i}" aria-label="Flip card ${i+1}"><span aria-hidden="true">✳</span></button>`).join('')}</div><p class="game-status" role="status" aria-live="polite">Pick any card. Trust your instincts.</p><div class="game-foot"><button class="text-button" data-action="preferences">Change preferences</button></div></section>`}
 else{const m=state.result;app.innerHTML=`<section class="screen game-screen enter">${top(3)}<div class="game-heading"><span class="step-label">IT’S A MATCH</span><h1>Tonight’s plot, sorted.</h1><p class="sub">The search is over. Make yourself comfortable.</p></div><article class="result-card"><div class="result-banner"><span>YOUR MOVIE FOR TONIGHT</span><span aria-hidden="true">✳</span></div><div class="result-body"><h2>${esc(m.title)}</h2><div class="movie-meta">${m.year} &nbsp;·&nbsp; ${m.runtime} min &nbsp;·&nbsp; ${m.genre}</div><p class="movie-desc">${esc(m.description)}</p><p class="why">${state.genre==='Surprise me'?'A little surprise':`Your ${state.genre.toLowerCase()} mood`}, ${state.duration==='any'?'with room to settle in':`comfortably within your ${state.duration==='short'?'under-90-minute':'90–120-minute'} window`}. Unlocked by your matching pair.</p><div class="result-actions"><a class="primary" href="https://www.imdb.com/find/?q=${encodeURIComponent(m.title+' '+m.year)}&s=tt" target="_blank" rel="noopener noreferrer">Movie details <span>↗</span></a><button class="text-button" data-action="play">Play for another pick ↻</button></div></div></article><p class="game-status">A curated movie pick. Streaming availability varies.</p></section>`}
}
function go(screen){turn++;state.screen=screen;state.locked=false;render();window.scrollTo({top:0,behavior:'instant'});const h=app.querySelector('h1');if(h){h.tabIndex=-1;h.focus({preventScroll:true})}}
function startGame(){if(!state.genre||!state.duration)return;let pool=matches().filter(m=>m.title!==state.result?.title);if(pool.length<3)pool=matches();let choices=shuffle(pool).slice(0,3);const icons=['🍿','🎬','🎟️'];state.deck=shuffle(choices.flatMap((movie,pair)=>[{pair,movie,icon:icons[pair]},{pair,movie,icon:icons[pair]}]));state.open=[];go('game')}
function flip(index){if(state.screen!=='game'||state.locked||state.open.includes(index))return;const card=state.deck[index];const b=app.querySelector(`[data-card="${index}"]`);b.classList.add('open');b.innerHTML=`<span aria-hidden="true">${card.icon}</span>`;b.setAttribute('aria-label',`Card ${index+1}: ${['popcorn','clapperboard','ticket'][card.pair]}`);b.setAttribute('aria-pressed','true');state.open.push(index);const status=app.querySelector('.game-status');if(state.open.length===1){status.textContent='Now find its match.';return}state.locked=true;const current=turn;const [a,z]=state.open;if(state.deck[a].pair===state.deck[z].pair){status.textContent='You found a match! Your movie is ready…';state.result=card.movie;app.querySelectorAll('.card.open').forEach(el=>el.classList.add('matched'));setTimeout(()=>{if(turn===current)go('result')},850)}else{status.textContent='Not quite. Remember these and try again.';setTimeout(()=>{if(turn!==current)return;state.open.forEach(i=>{let el=app.querySelector(`[data-card="${i}"]`);el.classList.remove('open');el.innerHTML='<span aria-hidden="true">✳</span>';el.setAttribute('aria-label',`Flip card ${i+1}`);el.removeAttribute('aria-pressed')});state.open=[];state.locked=false},1000)}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.genre){const g=b.dataset.genre;state.genre=g;render();app.querySelector(`[data-genre="${g}"]`).focus()}else if(b.dataset.duration){const d=b.dataset.duration;state.duration=d;render();app.querySelector(`[data-duration="${d}"]`).focus()}else if(b.dataset.card!==undefined)flip(Number(b.dataset.card));else if(b.dataset.action==='play')startGame();else if(b.dataset.action)go(b.dataset.action)});
render();
